openapi: 3.2.0
info:
  title: Confluent Cloud Connectors (connect/v1) API
  version: ''
  x-api-id: 46234552-5833-42eb-ba0f-883ad3f70d2b
  x-audience: external-public
  x-logo:
    url: https://assets.confluent.io/m/1661ef5e4ff82d3d/
  description: '# Introduction


    Note


    This documents the collection of Confluent Cloud APIs.'
servers:
- url: https://api.confluent.cloud
  description: Confluent Cloud API
tags:
- name: Connectors (connect/v1)
  description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


    API for Managed Connectors or Custom Connectors in Confluent Cloud.


    The API allows you to list, create, get, update and delete a Managed Connector or Custom Connector in Confluent Cloud.


    Connect metrics are available through the Metrics v2 API.


    Related guide: Confluent Cloud API and Managed Connectors.'
paths:
  /connect/v1/environments/{environment_id}/clusters/{kafka_cluster_id}/connectors:
    x-lifecycle-stage: General Availability
    parameters:
    - name: environment_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier of the environment this resource belongs to.
    - name: kafka_cluster_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier for the Kafka cluster.
    get:
      x-lifecycle-stage: General Availability
      operationId: listConnectv1Connectors
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Retrieve a list of "names" of the active connectors. You can then make a read request for a specific connector by name.'
      summary: List of Connectors
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      parameters: []
      responses:
        '200':
          description: Connector.
          content:
            application/json:
              schema:
                type: array
                description: List of connector names
                items:
                  type: string
                  description: Connector name
              example:
              - MyGcsLogsBucketConnector
              - MyS3BucketConnector
              - MyDatagenConnector
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.AccountNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/connect.v1.DefaultSystemError'
    post:
      x-lifecycle-stage: General Availability
      operationId: createConnectv1Connector
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Create a new connector. Returns the new connector information if successful.'
      summary: Create a Connector
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.v1.ConnectorWithOffsets'
              example:
                name: MyGcsLogsBucketConnector
                config:
                  cloud.environment: prod
                  cloud.provider: aws
                  connector.class: GcsSink
                  data.format: BYTES
                  flush.size: '1000'
                  gcs.bucket.name: APILogsBucket
                  gcs.credentials.config: '****************'
                  kafka.api.key: '****************'
                  kafka.api.secret: '****************'
                  kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                  kafka.region: us-west-2
                  name: MyGcsLogsBucketConnector
                  tasks.max: '1'
                  time.interval: DAILY
                  topics: APILogsTopic
                tasks:
                - connector: MyGcsLogsBucketConnector
                  task: 0
                type: sink
                offsets:
                - partition:
                    kafka_partition: 0
                    kafka_topic: APILogsTopic
                  offset:
                    kafka_offset: 1000
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
              example:
                error:
                  code: 400
                  message: Unauthorized
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: integer
                  message:
                    type: string
              example:
                error_code: 500
                message: Failed to find any class that implements Connector and which name matches io.confluent.connect.<connector-class>...
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the connector to create.
                config:
                  type: object
                  description: Configuration parameters for the connector. All values should be strings.
                  x-redact: true
                  required:
                  - connector.class
                  - name
                  - kafka.api.key
                  - kafka.api.secret
                  properties:
                    connector.class:
                      type: string
                      description: \[Required for Managed Connector, Ignored for Custom Connector\] The connector class name, e.g., BigQuerySink, GcsSink, etc.
                    name:
                      type: string
                      description: Name or alias of the class (plugin) for this connector. For custom connector, it must be the same as the name of the connector to create.
                    kafka.api.key:
                      type: string
                      description: The kafka cluster api key.
                    kafka.api.secret:
                      type: string
                      description: The kafka cluster api secret key.
                      x-redact: true
                    confluent.connector.type:
                      type: string
                      description: '\[Required for Custom Connector\] The connector type.

                        '
                      example: CUSTOM
                      default: MANAGED
                      x-extensible-enum:
                      - CUSTOM
                      - MANAGED
                    confluent.custom.plugin.id:
                      type: string
                      example: ccp-lq5m06
                      description: '\[Required for Custom Connector\] The custom plugin id of custom connector, e.g., `ccp-lq5m06`

                        '
                    confluent.custom.connection.endpoints:
                      type: string
                      description: '\[Optional for Custom Connector\] Egress endpoint(s) for the connector to use when attaching to the sink or source data system.

                        '
                    confluent.custom.schema.registry.auto:
                      type: string
                      description: '\[Optional for Custom Connector\] Automatically add the required schema registry properties in a custom connector config if schema registry is enabled.

                        '
                      example: 'FALSE'
                      default: 'FALSE'
                      x-extensible-enum:
                      - 'TRUE'
                      - 'FALSE'
                    confluent.custom.connect.plugin.runtime:
                      type: string
                      description: '\[Optional for Custom Connector\] The runtime of the custom connector plugin.

                        '
                      example: 3.9.0
                    confluent.custom.connect.java.version:
                      type: string
                      description: '\[Optional for Custom Connector\] The Java version of the custom connector plugin.

                        '
                      example: '17'
                  additionalProperties:
                    type: string
                    description: Other configuration parameters for the connector. All values should be strings. See the connector's docs for details.
                offsets:
                  $ref: '#/components/schemas/connect.v1.Offsets'
            examples:
              sink:
                value:
                  name: MyGcsLogsBucketConnector
                  config:
                    connector.class: GcsSink
                    data.format: BYTES
                    flush.size: '1000'
                    gcs.bucket.name: APILogsBucket
                    gcs.credentials.config: '****************'
                    kafka.api.key: '****************'
                    kafka.api.secret: '****************'
                    name: MyGcsLogsBucketConnector
                    tasks.max: '2'
                    time.interval: DAILY
                    topics: APILogsTopic
                  offsets:
                  - partition:
                      kafka_partition: 0
                      kafka_topic: APILogsTopic
                    offset:
                      kafka_offset: 1000
              source:
                value:
                  name: MySqlCdcSourceV2Connector_0
                  config:
                    connector.class: MySqlCdcSourceV2
                    output.data.format: JSON
                    flush.size: '1000'
                    database.hostname: 12.34.567.98
                    database.password: '****************'
                    database.port: '1234'
                    database.user: '****'
                    kafka.api.key: '****************'
                    kafka.api.secret: '****************'
                    name: MySqlCdcSourceV2Connector_0
                    tasks.max: '1'
                    time.interval: DAILY
                    topic.prefix: test
                  offsets:
                  - partition:
                      server: test
                    offset:
                      file: mysql-bin.000123
                      pos: 154
                      ts_sec: 1712907333
        description: ''
  /connect/v1/environments/{environment_id}/clusters/{kafka_cluster_id}/connectors?expand=info,status,id:
    x-lifecycle-stage: General Availability
    get:
      x-lifecycle-stage: General Availability
      operationId: listConnectv1ConnectorsWithExpansions
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Retrieve an object with the queried expansions of all connectors. Without `expand` query parameter, this list connector’s endpoint will return a list of only the connector names.'
      summary: List of Connectors with Expansions
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      responses:
        '200':
          description: Connector.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.v1.ConnectorExpansionMap'
              example:
                MyGcsLogsBucketConnector:
                  id:
                    id: lcc-xxxxx
                    id_type: ID
                  info:
                    name: MyGcsLogsBucketConnector
                    config:
                      cloud.environment: prod
                      cloud.provider: aws
                      connector.class: GcsSink
                      data.format: BYTES
                      flush.size: '1000'
                      gcs.bucket.name: APILogsBucket
                      gcs.credentials.config: '****************'
                      kafka.api.key: '****************'
                      kafka.api.secret: '****************'
                      kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                      kafka.region: us-west-2
                      name: MyGcsLogsBucketConnector
                      tasks.max: '1'
                      time.interval: DAILY
                      topics: APILogsTopic
                      type: sink
                  status:
                    name: MyGcsLogsBucketConnector
                    connector:
                      state: PROVISIONING
                      worker_id: MyGcsLogsBucketConnector
                      trace: ''
                    tasks: []
                    type: sink
                MyS3BucketConnector:
                  id:
                    id: lcc-xxxxx
                    id_type: ID
                  info:
                    name: MyS3BucketConnector
                    config:
                      cloud.environment: prod
                      cloud.provider: aws
                      connector.class: S3Sink
                      data.format: BYTES
                      flush.size: '1000'
                      s3.bucket: APILogsBucket
                      aws.access.key.id: '************'
                      aws.secret.access.key: '**********'
                      kafka.api.key: '****************'
                      kafka.api.secret: '****************'
                      kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                      kafka.region: us-west-2
                      name: MyS3BucketConnector
                      tasks.max: '1'
                      time.interval: DAILY
                      topics: APILogsTopic
                      type: source
                  status:
                    name: MyS3BucketConnector
                    connector:
                      state: FAILED
                      worker_id: MyS3BucketConnector
                      trace: 'There were some errors with your configuration:

                        topics: Provided Kafka ApiKey is invalid

                        kafka.api.secret: Provided Kafka ApiKey is invalid

                        '
                    tasks: []
                    type: sink
                MyDatagenConnector:
                  id:
                    id: lcc-xxxxx
                    id_type: ID
                  info:
                    name: MyDatagenConnector
                    config:
                      cloud.environment: prod
                      cloud.provider: aws
                      connector.class: DatagenSource
                      data.format: BYTES
                      flush.size: '1000'
                      quickstart: ORDERS
                      kafka.api.key: '****************'
                      kafka.api.secret: '****************'
                      kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                      kafka.region: us-west-2
                      name: MyDatagenConnector
                      tasks.max: '1'
                      time.interval: DAILY
                      topics: APILogsTopic
                      type: source
                  status:
                    name: MyDatagenConnector
                    connector:
                      state: RUNNING
                      worker_id: MyDatagenConnector
                      trace: ''
                    tasks:
                    - id: 0
                      msg: ''
                      state: RUNNING
                      worker_id: MyDatagenConnector
                    type: source
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.AccountNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/connect.v1.DefaultSystemError'
      parameters:
      - name: environment_id
        in: path
        schema:
          type: string
        required: true
        description: The unique identifier of the environment this resource belongs to.
      - name: kafka_cluster_id
        in: path
        schema:
          type: string
        required: true
        description: The unique identifier for the Kafka cluster.
      - name: expand
        in: query
        description: '- id : Returns metadata of each connector such as id and id type.

          - info : Returns metadata of each connector such as the configuration, task

          information, and type of connector.

          - status : Returns additional state information of each connector including their status and tasks.'
        schema:
          type: string
          enum:
          - id
          - info
          - status
  /connect/v1/environments/{environment_id}/clusters/{kafka_cluster_id}/connectors/{connector_name}/config:
    x-lifecycle-stage: General Availability
    parameters:
    - name: connector_name
      in: path
      schema:
        type: string
      required: true
      description: The unique name of the connector.
    - name: environment_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier of the environment this resource belongs to.
    - name: kafka_cluster_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier for the Kafka cluster.
    get:
      x-lifecycle-stage: General Availability
      operationId: getConnectv1ConnectorConfig
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Get the configuration for the connector.'
      summary: Read a Connector Configuration
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      responses:
        '200':
          description: Connector.
          content:
            application/json:
              schema:
                type: object
                description: Configuration parameters for the connector.
                required:
                - cloud.environment
                - cloud.provider
                - connector.class
                - name
                - kafka.endpoint
                - kafka.region
                - kafka.api.key
                - kafka.api.secret
                properties:
                  cloud.environment:
                    type: string
                    description: The cloud environment type.
                  cloud.provider:
                    type: string
                    description: The cloud service provider, e.g. aws, azure, etc.
                    x-extensible-enum:
                    - aws
                    - azure
                    - gcp
                  connector.class:
                    type: string
                    description: The connector class name. E.g. BigQuerySink, GcsSink, etc.
                  name:
                    type: string
                    description: Name or alias of the class (plugin) for this connector. For Custom Connector, it must be the same as connector_name.
                  kafka.endpoint:
                    type: string
                    description: The kafka cluster endpoint.
                  kafka.region:
                    type: string
                    description: The kafka cluster region.
                  kafka.api.key:
                    type: string
                    description: The kafka cluster api key.
                  kafka.api.secret:
                    type: string
                    description: The kafka cluster api secret key.
                    x-redact: true
                additionalProperties:
                  type: string
                  description: Other configuration parameters for the connector. See the connector's docs for the list of options.
              example:
                cloud.environment: prod
                cloud.provider: aws
                connector.class: GcsSink
                data.format: BYTES
                flush.size: '1000'
                gcs.bucket.name: APILogsBucket
                gcs.credentials.config: '****************'
                kafka.api.key: '****************'
                kafka.api.secret: '****************'
                kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                kafka.region: us-west-2
                name: MyGcsLogsBucketConnector
                tasks.max: '2'
                time.interval: DAILY
                topics: APILogsTopic
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.AccountNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/connect.v1.DefaultSystemError'
    put:
      x-lifecycle-stage: General Availability
      operationId: createOrUpdateConnectv1ConnectorConfig
      description: Create a new connector using the given configuration, or update the configuration for an existing connector. Returns information about the connector after the change has been made.
      summary: Create or Update a Connector Configuration
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Configuration parameters for the connector.
              required:
              - connector.class
              - name
              - kafka.api.key
              - kafka.api.secret
              properties:
                connector.class:
                  type: string
                  description: \[Required for Managed Connector, Ignored for Custom Connector\] The connector class name. E.g. BigQuerySink, GcsSink, etc.
                name:
                  type: string
                  description: Name or alias of the class (plugin) for this connector.
                kafka.api.key:
                  type: string
                  description: The kafka cluster api key.
                kafka.api.secret:
                  type: string
                  description: The kafka cluster api secret key.
                  x-redact: true
                confluent.connector.type:
                  type: string
                  description: '\[Required for Custom Connector\] The connector type.

                    '
                  example: CUSTOM
                  default: MANAGED
                  x-extensible-enum:
                  - CUSTOM
                  - MANAGED
                confluent.custom.plugin.id:
                  type: string
                  example: ccp-lq5m06
                  description: '\[Required for Custom Connector\] The custom plugin id of custom connector, e.g., `ccp-lq5m06`

                    '
                confluent.custom.connection.endpoints:
                  type: string
                  description: '\[Optional for Custom Connector\] Egress endpoint(s) for the connector to use when attaching to the sink or source data system.

                    '
                confluent.custom.schema.registry.auto:
                  type: string
                  description: '\[Optional for Custom Connector\] Automatically add the required schema registry properties in a custom connector config if schema registry is enabled.

                    '
                  example: 'FALSE'
                  default: 'FALSE'
                  x-extensible-enum:
                  - 'TRUE'
                  - 'FALSE'
                confluent.custom.connect.plugin.runtime:
                  type: string
                  description: '\[Optional for Custom Connector\] The runtime of the custom connector plugin. By default this is the latest version available. If not provided this config is updated internally to reflect the version used.

                    '
                  example: 3.9.0
                confluent.custom.connect.java.version:
                  type: string
                  description: '\[Optional for Custom Connector\] The Java version of the custom connector plugin. By default this is the latest version supported by the latest runtime. If not provided this config is updated internally to reflect the version used.

                    '
                  example: '17'
              additionalProperties:
                type: string
                description: Other configuration parameters for the connector. All values should be strings. See the connector's docs for details.
            example:
              connector.class: GcsSink
              data.format: BYTES
              flush.size: '1000'
              gcs.bucket.name: APILogsBucket
              gcs.credentials.config: '****************'
              kafka.api.key: '****************'
              kafka.api.secret: '****************'
              name: MyGcsLogsBucketConnector
              tasks.max: '2'
              time.interval: DAILY
              topics: APILogsTopic
        description: Configuration parameters for the connector. All values should be strings.
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.v1.Connector'
              example:
                name: MyGcsLogsBucketConnector
                config:
                  cloud.environment: prod
                  cloud.provider: aws
                  connector.class: GcsSink
                  data.format: BYTES
                  flush.size: '1000'
                  gcs.bucket.name: APILogsBucket
                  gcs.credentials.config: '****************'
                  kafka.api.key: '****************'
                  kafka.api.secret: '****************'
                  kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                  kafka.region: us-west-2
                  name: MyGcsLogsBucketConnector
                  tasks.max: '2'
                  time.interval: DAILY
                  topics: APILogsTopic
                tasks:
                - connector: MyGcsLogsBucketConnector
                  task: 0
                - connector: MyGcsLogsBucketConnector
                  task: 1
                type: sink
        '400':
          $ref: '#/components/responses/connect.v1.BadRequestError'
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.AccountNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: integer
                  message:
                    type: string
              example:
                error_code: 500
                message: Failed to find any class that implements Connector and which name matches io.confluent.connect.<connector-class>...
  /connect/v1/environments/{environment_id}/clusters/{kafka_cluster_id}/connectors/{connector_name}:
    x-lifecycle-stage: General Availability
    parameters:
    - name: connector_name
      in: path
      schema:
        type: string
      required: true
      description: The unique name of the connector.
    - name: environment_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier of the environment this resource belongs to.
    - name: kafka_cluster_id
      in: path
      schema:
        type: string
      required: true
      description: The unique identifier for the Kafka cluster.
    get:
      x-lifecycle-stage: General Availability
      operationId: readConnectv1Connector
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Get information about the connector.'
      summary: Read a Connector
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      responses:
        '200':
          description: Connector.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.v1.Connector'
              example:
                name: MyGcsLogsBucketConnector
                config:
                  cloud.environment: prod
                  cloud.provider: aws
                  connector.class: GcsSink
                  data.format: BYTES
                  flush.size: '1000'
                  gcs.bucket.name: APILogsBucket
                  gcs.credentials.config: '****************'
                  kafka.api.key: '****************'
                  kafka.api.secret: '****************'
                  kafka.endpoint: SASL_SSL://pkc-xxxxx.us-west-2.aws.confluent.cloud:9092
                  kafka.region: us-west-2
                  name: MyGcsLogsBucketConnector
                  tasks.max: '1'
                  time.interval: DAILY
                  topics: APILogsTopic
                tasks:
                - connector: MyGcsLogsBucketConnector
                  task: 0
                type: sink
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.AccountNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/connect.v1.DefaultSystemError'
    delete:
      x-lifecycle-stage: General Availability
      operationId: deleteConnectv1Connector
      description: '![General Availability](#section/Versioning/API-Lifecycle-Policy)


        Delete a connector. Halts all tasks and deletes the connector configuration.'
      summary: Delete a Connector
      tags:
      - Connectors (connect/v1)
      security:
      - cloud-api-key: []
      - confluent-sts-access-token: []
      responses:
        '200':
          $ref: '#/components/responses/connect.v1.OK'
        '401':
          $ref: '#/components/responses/connect.v1.UnauthenticatedError'
        '404':
          $ref: '#/components/responses/connect.v1.ResourceNotFoundError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/connect.v1.DefaultSystemError'
components:
  schemas:
    connect.v1.ConnectorError:
      type: object
      properties:
        error:
          type: object
          description: Connector Error with error code and message.
          properties:
            code:
              type: integer
              description: Error code for the type of error
            message:
              type: string
              description: Human readable error message
    connect.v1.ConnectorWithOffsets:
      type: object
      properties:
        name:
          type: string
          description: Name of the connector
        config:
          type: object
          description: 'Configuration parameters for the connector. These configurations

            are the minimum set of key-value pairs which can be used to

            define how the connector connects Kafka to the external system.

            Some of these key-value pairs are common to all the connectors, such as

            connection parameters to Kafka, connector metadata, etc. The list

            of common connector configurations is as follows

            - cloud.environment

            - cloud.provider

            - connector.class

            - kafka.api.key

            - kafka.api.secret

            - kafka.endpoint

            - kafka.region

            - name

            A specific connector such as `GcsSink` would have additional

            parameters such as `gcs.bucket.name`, `flush.size`, etc.'
          required:
          - cloud.environment
          - cloud.provider
          - connector.class
          - name
          - kafka.endpoint
          - kafka.region
          - kafka.api.key
          - kafka.api.secret
          properties:
            cloud.environment:
              type: string
              description: The cloud environment type.
            cloud.provider:
              type: string
              description: The cloud service provider, e.g. aws, azure, etc.
              x-extensible-enum:
              - aws
              - azure
              - gcp
            connector.class:
              type: string
              description: The connector class name. E.g. BigQuerySink, GcsSink, etc.
            name:
              type: string
              description: Name or alias of the class (plugin) for this connector.
            kafka.endpoint:
              type: string
              description: The Kafka cluster endpoint.
            kafka.region:
              type: string
              description: The Kafka cluster region.
            kafka.api.key:
              type: string
              description: The Kafka cluster API key.
            kafka.api.secret:
              type: string
              description: The Kafka cluster API secret.
              x-redact: true
          additionalProperties:
            type: string
        tasks:
          type: array
          description: List of active tasks generated by the connector
          items:
            type: object
            properties:
              connector:
                type: string
                description: The name of the connector the task belongs to
              task:
                type: integer
                description: Task ID within the connector
            required:
            - connector
            - task
        type:
          type: string
          description: Type of connector, sink or source
          enum:
          - sink
          - source
        offsets:
          $ref: '#/components/schemas/connect.v1.Offsets'
      required:
      - name
      - config
    connect.v1.ConnectorExpansionMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/connect.v1.ConnectorExpansion'
    connect.v1.Offsets:
      type: array
      description: Array of offsets which are categorised into partitions.
      items:
        type: object
        properties:
          partition:
            type: object
            additionalProperties: true
            description: "The partition information. For sink connectors this is the kafka topic and \npartition. For source connectors this is depends on the partitions defined by the \nsource connector. For example, the table which this task is pulling data from in a\nJDBC based MySQL source connector.\nPlease refer to the [documentation](https://docs.confluent.io/cloud/current/connectors/offsets.html#manage-offsets-for-fully-managed-connectors-in-ccloud) for \nmore information."
          offset:
            type: object
            additionalProperties: true
            description: "The offset of the partition. For sink connectors this is the kafka offset. For \nsource connectors this is depends on the offset defined by the source connector. \nFor example, the timestamp and incrementing column info in a table, for a JDBC based \nMySQL source connector.\nPlease refer to the [documentation](https://docs.confluent.io/cloud/current/connectors/offsets.html#manage-offsets-for-fully-managed-connectors-in-ccloud) for \nmore information."
    connect.v1.ConnectorExpansion:
      type: object
      description: Name of connector
      properties:
        id:
          type: object
          description: The ID of connector.
          properties:
            id:
              type: string
              description: The ID of the connector.
            id_type:
              type: string
              description: Type of the value in the `id` property.
        info:
          type: object
          description: Metadata of the connector.
          properties:
            name:
              type: string
              description: Name of the connector.
            config:
              type: object
              description: "Configuration parameters for the connector. These configurations\nare the minimum set of key-value pairs (KVP) which are used to\ndefine how the connector connects Kafka to the external system.\nSome of these KVPs are common to all the connectors, such as\nconnection parameters to Kafka, connector metadata, etc. The list\nof common connector configurations is as follows\n\n  - cloud.environment\n  - cloud.provider\n  - connector.class\n  - kafka.api.key\n  - kafka.api.secret\n  - kafka.endpoint\n  - kafka.region\n  - name\n\nFor example, a connector like `GcsSink` would have additional\nparameters such as `gcs.bucket.name`, `flush.size`, etc."
              required:
              - cloud.environment
              - cloud.provider
              - connector.class
              - name
              - kafka.endpoint
              - kafka.region
              - kafka.api.key
              - kafka.api.secret
              properties:
                cloud.environment:
                  type: string
                  description: The cloud environment type.
                cloud.provider:
                  type: string
                  description: The cloud service provider, e.g. aws, azure, etc.
                  x-extensible-enum:
                  - aws
                  - azure
                  - gcp
                connector.class:
                  type: string
                  description: The connector class name. E.g. BigQuerySink, GcsSink, etc.
                name:
                  type: string
                  description: Name or alias of the class (plugin) for this connector.
                kafka.endpoint:
                  type: string
                  description: The kafka cluster endpoint.
                kafka.region:
                  type: string
                  description: The kafka cluster region.
                kafka.api.key:
                  type: string
                  description: The kafka cluster api key.
                kafka.api.secret:
                  type: string
                  description: The kafka cluster api secret key.
                  x-redact: true
              additionalProperties:
                type: string
        status:
          type: object
          description: Status of the connector and its tasks.
          properties:
            name:
              type: string
              description: The name of the connector.
            type:
              type: string
              description: Type of connector, sink or source.
              enum:
              - sink
              - source
            connector:
              type: object
              description: A map containing connector status.
              required:
              - state
              - worker_id
              properties:
                state:
                  type: string
                  description: The state of the connector.
                  enum:
                  - NONE
                  - PROVISIONING
                  - RUNNING
                  - DEGRADED
                  - FAILED
                  - PAUSED
                  - DELETED
                worker_id:
                  type: string
                  description: The worker ID of the connector.
                trace:
                  type: string
                  description: Exception message in case of an error.
            tasks:
              type: array
              description: A map containing the task status.
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of task.
                  state:
                    type: string
                    description: The state of the task.
                  worker_id:
                    type: string
                    description: The worker ID of the task.
                  msg:
                    type: string
                required:
                - id
                - state
                - worker_id
          required:
          - name
          - type
          - connector
    connect.v1.Connector:
      type: object
      properties:
        name:
          type: string
          description: Name of the connector
        config:
          type: object
          description: 'Configuration parameters for the connector. These configurations

            are the minimum set of key-value pairs (KVP) which can be used to

            define how the connector connects Kafka to the external system.

            Some of these KVPs are common to all the connectors, such as

            connection parameters to Kafka, connector metadata, etc. The list

            of common connector configurations is as follows


            - cloud.environment

            - cloud.provider

            - connector.class

            - kafka.api.key

            - kafka.api.secret

            - kafka.endpoint

            - kafka.region

            - name


            A specific connector such as `GcsSink` would have additional

            parameters such as `gcs.bucket.name`, `flush.size`, etc.'
          required:
          - cloud.environment
          - cloud.provider
          - connector.class
          - name
          - kafka.endpoint
          - kafka.region
          - kafka.api.key
          - kafka.api.secret
          properties:
            cloud.environment:
              type: string
              description: The cloud environment type.
            cloud.provider:
              type: string
              description: The cloud service provider, e.g. aws, azure, etc.
              x-extensible-enum:
              - aws
              - azure
              - gcp
            connector.class:
              type: string
              description: The connector class name. E.g. BigQuerySink, GcsSink, etc.
            name:
              type: string
              description: Name or alias of the class (plugin) for this connector.
            kafka.endpoint:
              type: string
              description: The kafka cluster endpoint.
            kafka.region:
              type: string
              description: The kafka cluster region.
            kafka.api.key:
              type: string
              description: The kafka cluster api key.
            kafka.api.secret:
              type: string
              description: The kafka cluster api secret key.
              x-redact: true
          additionalProperties:
            type: string
        tasks:
          type: array
          description: List of active tasks generated by the connector
          items:
            type: object
            properties:
              connector:
                type: string
                description: The name of the connector the task belongs to
              task:
                type: integer
                description: Task ID within the connector
            required:
            - connector
            - task
        type:
          type: string
          description: Type of connector, sink or source
          enum:
          - sink
          - source
      required:
      - name
      - config
  responses:
    connect.v1.BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.v1.ConnectorError'
          example:
            error:
              code: 400
              message: Bad Request
    connect.v1.DefaultSystemError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.v1.ConnectorError'
          example:
            error:
              code: 500
              message: Oops, something went wrong
    RateLimitError:
      description: Rate Limit Exceeded
      headers:
        X-Request-Id:
          schema:
            type: string
          description: The unique identifier for the API request.
        X-RateLimit-Limit:
          schema:
            type: integer
          description: The maximum number of requests you're permitted to make per time period.
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: The number of requests remaining in the current rate limit window.
        X-RateLimit-Reset:
          schema:
            type: integer
          description: "The relative time in seconds until the current rate-limit window resets.  \n  \n**Important:** This differs from Github and Twitter's same-named header which uses UTC epoch seconds. We use relative time to avoid client/server time synchronization issues."
        Retry-After:
          schema:
            type: integer
          description: The number of seconds to wait until the rate limit window resets. Only sent when the rate limit is reached.
    connect.v1.AccountNotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.v1.ConnectorError'
          example:
            error:
              code: 404
              message: account not found
    connect.v1.ResourceNotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.v1.ConnectorError'
          example:
            error:
              code: 404
              message: resource not found
    connect.v1.OK:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type:
                - object
                - 'null'
          example:
            error: null
    connect.v1.UnauthenticatedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.v1.ConnectorError'
          example:
            error:
              code: 401
              message: Unauthorized
  securitySchemes:
    cloud-api-key:
      type: http
      scheme: basic
      description: Authenticate with Cloud API Keys using HTTP Basic Auth. Treat the Cloud API Key ID as the username and Cloud API Key Secret as the password.
    confluent-sts-access-token:
      type: oauth2
      description: Authenticate with Confluent API using this credentials (JSON Web Tokens) following OAuth 2.0.
      flows:
        clientCredentials:
          tokenUrl: https://api.confluent.cloud/sts/v1/oauth2/token
          scopes: {}
    global-api-key:
      type: http
      scheme: basic
      description: Authenticate with Global API Keys using HTTP Basic Auth. Treat the Global API Key ID as the username and Global API Key Secret as the password.
    resource-api-key:
      type: http
      scheme: basic
      description: Authenticate with resource-specific API Keys using HTTP Basic Auth. Treat the resource-specific API Key ID as the username and resource-specific API Key Secret as the password.
    external-access-token:
      type: oauth2
      description: Authenticate with Confluent API using this credentials (JSON Web Tokens) following OAuth 2.0.
      flows:
        clientCredentials:
          tokenUrl: https://api.confluent.cloud/sts/v1/oauth2/token
          scopes: {}
    oauth:
      type: oauth2
      description: Authenticate with OAuth 2.0. Currently this is only supported for partner APIs.
      flows:
        clientCredentials:
          tokenUrl: /oauth2/token
          scopes:
            partner:alter: enables partners to alter entitlements
            partner:create: enables partners to create entitlements and signup on behalf of customers
            partner:delete: enables partners to delete entitlements and organizations
            partner:describe: enables partners to read and list entitlements and organizations
x-tagGroups:
- name: Identity Access Management (v2)
  tags:
  - API Keys (iam/v2)
  - Users (iam/v2)
  - Service Accounts (iam/v2)
  - Invitations (iam/v2)
  - IP Groups (iam/v2)
  - IP Filters (iam/v2)
  - IP Filter Summaries (iam/v2)
  - Role Bindings (iam/v2)
  - Identity Providers (iam/v2)
  - Jwks (iam/v2)
  - Identity Pools (iam/v2)
  - Group Mappings (iam/v2/sso)
  - Certificate Authorities (iam/v2)
  - Certificate Identity Pools (iam/v2)
- name: Org API (v2)
  tags:
  - Environments (org/v2)
  - Organizations (org/v2)
- name: Notifications API (v1)
  tags:
  - Subscriptions (notifications/v1)
  - Integrations (notifications/v1)
  - Notification Types (notifications/v1)
  - Resource Preferences (notifications/v1)
  - Resource Subscriptions (notifications/v1)
  - User Notifications (notifications/v1)
- name: Cluster Mgmt for Kafka (v2)
  tags:
  - Clusters (cmk/v2)
- name: Cluster Mgmt for ksqlDB (v2)
  tags:
  - Clusters (ksqldbcm/v2)
- name: Connect API (v1)
  tags:
  - Connectors (connect/v1)
  - Lifecycle (connect/v1)
  - Status (connect/v1)
  - Managed Connector Plugins (connect/v1)
  - Offsets (connect/v1)
  - Custom Connector Plugins (connect/v1)
  - Presigned Urls (connect/v1)
  - Custom Connector Runtimes (connect/v1)
- name: Connect Artifact Management (v1)
  tags:
  - Connect Artifacts (cam/v1)
  - Presigned Urls (cam/v1)
- name: Kafka API (v3)
  tags:
  - Cluster (v3)
  - Configs (v3)
  - ACL (v3)
  - Consumer Group (v3)
  - Partition (v3)
  - Topic (v3)
  - Records (v3)
  - Cluster Linking (v3)
  - Share Group (v3)
  - Streams Group (v3)
- name: Service Quota API (v1)
  tags:
  - Applied Quotas (service-quota/v1)
  - Scopes (service-quota/v1)
- name: Partner API (v2)
  tags:
  - Entitlements (partner/v2)
  - Organizations (partner/v2)
  - Signup (partner/v2)
- name: Cluster Mgmt for Schema Registry (v2)
  tags:
  - Regions (srcm/v2)
  - Clusters (srcm/v2)
- name: Cluster Mgmt for Schema Registry (v3)
  tags:
  - Clusters (srcm/v3)
- name: Schema Registry API (v1)
  tags:
  - Compatibility (v1)
  - Config (v1)
  - Contexts (v1)
  - Exporters (v1)
  - Modes (v1)
  - Schemas (v1)
  - Subjects (v1)
  - Key Encryption Keys (v1)
  - Data Encryption Keys (v1)
- name: Catalog API (v1)
  tags:
  - Entity (v1)
  - Search (v1)
  - Types (v1)
- name: Stream Sharing API (v1)
  tags:
  - Provider Shared Resources (cdx/v1)
  - Provider Shares (cdx/v1)
  - Consumer Shared Resources (cdx/v1)
  - Consumer Shares (cdx/v1)
  - Shared Tokens (cdx/v1)
  - Opt Ins (cdx/v1)
- name: Networking (v1)
  tags:
  - Networks (networking/v1)
  - Peerings (networking/v1)
  - Transit Gateway Attachments (networking/v1)
  - Private Link Accesses (networking/v1)
  - Network Link Services (networking/v1)
  - Network Link Endpoints (networking/v1)
  - Network Link Service Associations (networking/v1)
  - IP Addresses (networking/v1)
  - Private Link Attachments (networking/v1)
  - Private Link Attachment Connections (networking/v1)
  - DNS Forwarders (networking/v1)
  - Access Points (networking/v1)
  - DNS Records (networking/v1)
  - Gateways (networking/v1)
- name: Security Token Service (v1)
  tags:
  - OAuth Tokens (sts/v1)
- name: Kafka Quota (v1)
  tags:
  - Client Quotas (kafka-quotas/v1)
- name: Bring Your Own Key (BYOK) Management (v1)
  tags:
  - Keys (byok/v1)
- name: Billing API (v1)
  tags:
  - Costs (billing/v1)
- name: Compute Pool Mgmt for Flink (v2)
  tags:
  - Compute Pools (fcpm/v2)
  - Regions (fcpm/v2)
  - Org Compute Pool Configs (fcpm/v2)
- name: SQL API (v1)
  tags:
  - Statements (sql/v1)
  - Statement Results (sql/v1)
  - Statement Exceptions (sql/v1)
  - Connections (sql/v1)
  - Agents (sql/v1)
  - Tools (sql/v1)
  - Materialized Tables (sql/v1)
  - Materialized Table Versions (sql/v1)
- name: Provider Integration Management (v1)
  tags:
  - Integrations (pim/v1)
- name: Provider Integration Management (v2)
  tags:
  - Integrations (pim/v2)
- name: Artifact API (v1)
  tags:
  - Flink Artifacts (artifact/v1)
  - Presigned Urls (artifact/v1)
  - Flink Artifact Versions (artifact/v1)
- name: Custom Code Logging API (v1)
  tags:
  - Custom Code Loggings (ccl/v1)
- name: Tableflow (v1)
  tags:
  - Regions (tableflow/v1)
  - Tableflow Topics (tableflow/v1)
  - Catalog Integrations (tableflow/v1)
- name: Custom Connect Plugin Management (v1)
  tags:
  - Custom Connect Plugins (ccpm/v1)
  - Presigned Urls (ccpm/v1)
  - Custom Connect Plugin Versions (ccpm/v1)
- name: Unified Stream Manager (v1)
  tags:
  - Kafka Clusters (usm/v1)
  - Connect Clusters (usm/v1)
- name: Endpoint (v1)
  tags:
  - Endpoints (endpoint/v1)
- name: Real Time Context Engine (v1)
  tags:
  - Rtce Topics (rtce/v1)
  - Regions (rtce/v1)
- name: Analytics (v1alpha1)
  tags:
  - Statements (query/v1alpha1)
